//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServer.WebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TropicalServer.com/WebService", ConfigurationName="WebService.TropicalServerWebServiceSoap")]
    public interface TropicalServerWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TropicalServer.com/WebService/getCustId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCustId(string prefix);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TropicalServerWebServiceSoapChannel : TropicalServer.WebService.TropicalServerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TropicalServerWebServiceSoapClient : System.ServiceModel.ClientBase<TropicalServer.WebService.TropicalServerWebServiceSoap>, TropicalServer.WebService.TropicalServerWebServiceSoap {
        
        public TropicalServerWebServiceSoapClient() {
        }
        
        public TropicalServerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TropicalServerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TropicalServerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TropicalServerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getCustId(string prefix) {
            return base.Channel.getCustId(prefix);
        }
    }
}
